---
title: Make your own way!
timezone: Russia/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/blog/:title"
name: Make your own way
description: A blog about programming and stuff
google_verification:
include:
- ".htaccess"
exclude:
- README.md
- LICENSE
sass:
  style: compressed
  sass_dir: _sass
markdown: markdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
